### ISSUE TITLE
Requests for script.

### ISSUE THREAD

**Issue by TinyTigerPan** [sail-sg/MDT#10]
Hi, thanks for your wonderful job. Can you provide full data to draw Fig.1 in your paper, or your script to draw Fig.1, it may help me a lot.
Thanks!

**Comment by gasvn** [comment]
Do you mean the training time comparision figure? Give me you mail and I will send it to you.

**Comment by TinyTigerPan** [comment]
Yes, the Fig.1 Down: learning progress comparison between DiT and MDT. 
Many thanks to your reply, it is really helpful. 
Here is my email: zhouxianpan@zju.edu.cn

**Comment by seuld** [comment]
@gasvn, hi! 
Could you also send me this script (including training weights for DiT-S/2)?
My email: d49125610@gmail.com
Thanks!

**Comment by gasvn** [comment]
I have send it to you.

**Comment by weny911** [comment]
> 我已经发给你了。

Dear author, I hope I didn't disturb you. Could you please send me a pre training weight for **DiT-B/2**? Thank you very much
