### ISSUE TITLE
Module Import error in train_util.py

### ISSUE THREAD

**Issue by Bhavay-2001** [sail-sg/MDT#11]
Hi, I'm trying to run the file train_util.py you provided but it throws an error - "ModuleNotFoundError: No module named 'diffusers'". I read the code and you have basically imported AutoEncoder.py from the diffusers module of the hugging face repository but how it is done? How have you made the import statement work since you haven't cloned the hugging face GitHub repository.

**Comment by gasvn** [comment]
Just install diffusers with `pip install diffusers`
