### ISSUE TITLE
About calculation of FID score

### ISSUE THREAD

**Issue by ILLLLUSION** [sail-sg/MDT#18]
I have a question. In the readme of the evaluations file, the reference batch is the 10,000 real images in the data set, and the others are 50,000 sample images generated by the model after training in different data sets. 
This line of code 

> python evaluator.py VIRTUAL_imagenet256_labeled.npz admnet_guided_upsampled_imagenet256.npz

uses 10,000 real pictures and 50,000 generated sample pictures for calculation. Is the calculated FID score called FID10K or FID50K? When calculating FID10K and FID50K, do 10K and 50K represent the number of real pictures or the number of sample pictures? I am a beginner at generating models and I still don’t understand many concepts. I hope it didn't bother you and I look forward to your answer.

**Comment by gasvn** [comment]
Hi, 50K usually represents the number of sample pictures. And I follow this to evaluate the model.  https://github.com/openai/guided-diffusion/tree/main/evaluations

**Comment by ILLLLUSION** [comment]
> Hi, 50K usually represents the number of sample pictures. And I follow this to evaluate the model.  https://github.com/openai/guided-diffusion/tree/main/evaluations

Thank you very much for your answer .

**Comment by ILLLLUSION** [comment]
> Hi, 50K usually represents the number of sample pictures. And I follow this to evaluate the model. https://github.com/openai/guided-diffusion/tree/main/evaluations

I have another question，In iddpm's article, it is mentioned that they use the ema_0.9999 model. The model.pt file and the ema_0.9999.pt file in the training results. Which sample generated by the two model weights is better? May I ask which model you used to generate the image when you finally calculated the FID score?

**Comment by gasvn** [comment]
I used the ema model following previous works. Didn't test the model.pt on our side.

**Comment by weny911** [comment]
Dear friend, I have some questions about the evaluation generation. Could you please add me to WeChat or email for consultation? Thank you very much！**codetruth@163.com**
