### ISSUE TITLE
can not find the file of "mdt_xl2_v2_ckpt"

### ISSUE THREAD

**Issue by mapengsen** [sail-sg/MDT#22]
MODEL_PATH=output_mdt_xl2/mdt_xl2_v2_ckpt.pt

how can i get the model of output_mdt_xl2/mdt_xl2_v2_ckpt.pt?

Thanks

**Comment by gasvn** [comment]
Hi, the checkpoint for v2 is in https://huggingface.co/shgao/MDT-XL2/tree/main as well.
