### ISSUE TITLE
MDTv2 Weights Error

### ISSUE THREAD

**Issue by xv994** [sail-sg/MDT#26]
Hey! Thank you for your paper and code! They are both great and interesting! But I have some questions, I want to ask for your help.

When I used the MDTv2 weights downloaded from huggingface hub to run the 'infer_mdt.py', I faced this problem. It shows that there are some missing layers and unexpected layers. I just want to know what happens.
![image](https://github.com/sail-sg/MDT/assets/74281061/1f2b63d6-c8b4-4fcf-a6cc-04e4672c8ce6)

**Comment by gasvn** [comment]
Thank you for the feedback! I have fixed this bug. You can pull the latest code now.
This python was written for mdtv1, and we need to change the decoder_layer from 2 to 4 for mdtv2. 
<img width="640" alt="image" src="https://github.com/sail-sg/MDT/assets/20515144/8cac4925-26d7-476b-ba2b-50e42b6b52c7">

**Comment by xv994** [comment]
Thank you for your reply. The problem has been dealt with. But, unfortunately, I have had another problem again.
When I run the 'infer_mdt.py', it reminds me of that. I have no idea how to solve it. I have searched for issues, but there is no useful information.
![image](https://github.com/sail-sg/MDT/assets/74281061/081a9285-77dc-4fe3-82f5-39cec81d12b0)

**Comment by gasvn** [comment]
Please check this one #27  Let me know if you still face this problem

**Comment by xv994** [comment]
Ohhhh! Maybe I forgot to `pip install -e .`. It works now. Thank you for your reply! How nice you are!
