### ISSUE TITLE
Visualization problem

### ISSUE THREAD

**Issue by ZH3nGsQ** [sail-sg/MDT#27]
When I use your pretrained model and run the infer_mdt.py to generate images. The outcome--"sample.jpg" was very noisy. Can you tell me what is happened?
![{Q0 B6C82HN)QP7PHZU0O8G](https://github.com/sail-sg/MDT/assets/163538949/d226ec2e-eaaf-4cf9-9208-f8a98069f597)

**Comment by ZH3nGsQ** [comment]
And I also encountered with another problem in training stage is that--"RuntimeError: a leaf Variable that requires grad is being used in an in-place operation." I don't know how to solve that.

**Comment by xv994** [comment]
hey bro, I met some problems when I ran the "infer_mdt.py". Can you tell me how can I run this .py file?
![image](https://github.com/sail-sg/MDT/assets/74281061/133bec9d-ee02-4e23-a1d4-482cb914faaa)
Should I change or add some parameters?

**Comment by gasvn** [comment]
Have you do the `pip install -e .`? I tested on my side, and it works fine.
<img width="650" alt="image" src="https://github.com/sail-sg/MDT/assets/20515144/f29ba467-73e9-480f-954a-79dbc02bedba">

**Comment by gasvn** [comment]
> When I use your pretrained model and run the infer_mdt.py to generate images. The outcome--"sample.jpg" was very noisy. Can you tell me what is happened? ![{Q0 B6C82HN)QP7PHZU0O8G](https://private-user-images.githubusercontent.com/163538949/313194441-d226ec2e-eaaf-4cf9-9208-f8a98069f597.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MzU0MzAsIm5iZiI6MTcxMDUzNTEzMCwicGF0aCI6Ii8xNjM1Mzg5NDkvMzEzMTk0NDQxLWQyMjZlYzJlLWVhYWYtNGNmOS05MjA4LWY4YTk4MDY5ZjU5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNVQyMDM4NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OGNhODY5ODcwYzAxMWZkNDU2ZWExOGY2ZGNlYWJjYWFjM2RmZmQ4OTI1ODU2OGU3ZWYyOTgxNDQ5OTM2NmFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WtInugCh0KbxiBKsekVJ_yyxzVIfOrNoaqqfoseChQU)

did you download the pretrained model from hugglingface?

**Comment by ZH3nGsQ** [comment]
> hey bro, I met some problems when I ran the "infer_mdt.py". Can you tell me how can I run this .py file? ![image](https://private-user-images.githubusercontent.com/74281061/313226864-133bec9d-ee02-4e23-a1d4-482cb914faaa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NzY2MDMsIm5iZiI6MTcxMDU3NjMwMywicGF0aCI6Ii83NDI4MTA2MS8zMTMyMjY4NjQtMTMzYmVjOWQtZWUwMi00ZTIzLWExZDQtNDgyY2I5MTRmYWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDA4MDUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyNmRiY2IwNjU0YWIzYWQ4YmNiMzdiYzk3NTlmNDVhZmZmNTc3ZDk4NGU1ZDA5MDllOTAxMDQ3Mjg1NmZjMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ien6J-7Buo0ZVvbogw-IJArtLRBYFWB0a76xy8A-qho) Should I change or add some parameters?

I didn't change or add any parameters.

**Comment by ZH3nGsQ** [comment]
> > When I use your pretrained model and run the infer_mdt.py to generate images. The outcome--"sample.jpg" was very noisy. Can you tell me what is happened? ![{Q0 B6C82HN)QP7PHZU0O8G](https://private-user-images.githubusercontent.com/163538949/313194441-d226ec2e-eaaf-4cf9-9208-f8a98069f597.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MzU0MzAsIm5iZiI6MTcxMDUzNTEzMCwicGF0aCI6Ii8xNjM1Mzg5NDkvMzEzMTk0NDQxLWQyMjZlYzJlLWVhYWYtNGNmOS05MjA4LWY4YTk4MDY5ZjU5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNVQyMDM4NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OGNhODY5ODcwYzAxMWZkNDU2ZWExOGY2ZGNlYWJjYWFjM2RmZmQ4OTI1ODU2OGU3ZWYyOTgxNDQ5OTM2NmFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WtInugCh0KbxiBKsekVJ_yyxzVIfOrNoaqqfoseChQU)
> 
> did you download the pretrained model from hugglingface?

I already download pretrained model "mdt_xl2_v2_ckpt.pt" from hugging face. And I use the **pip install -e .** . The outcome is still worse.

**Comment by gasvn** [comment]
Did you find any warning or so? If looks like the pretrained model is not correctly loaded.
