### ISSUE TITLE
Train Custom Dataset

### ISSUE THREAD

**Issue by xv994** [sail-sg/MDT#28]
Hey, I am coming too. infer_mdt.py works now, but when I trained my dataset, I had a new problem as below.
![image](https://github.com/sail-sg/MDT/assets/74281061/954f845c-4ad2-4636-8379-e5597659d516)
Do you guys know why it has a segmentation error? Please help me!

**Comment by xv994** [comment]
When I ran the MDTv1, I met the same problem.
![image](https://github.com/sail-sg/MDT/assets/74281061/a8316481-229e-4021-98d7-42435b34cca9)
My GPU is 3090 24GB. batch_size = 1

**Comment by gasvn** [comment]
It seems like a environment issue. Can you try to reinstall your pytorch environment and also the cuda and cudnn?

**Comment by weny911** [comment]
Can I add you to WeChat communication?

**Comment by xv994** [comment]
> Can I add you to WeChat communication?

give me your email address or wechat account

**Comment by liwenyang-911** [comment]
codetruth@163.com
Thanks!!

**Comment by weny911** [comment]
> > Can I add you to WeChat communication?
> 
> give me your email address or wechat account

[codetruth@163.com](mailto:codetruth@163.com)

**Comment by xv994** [comment]
> > > Can I add you to WeChat communication?
> > 
> > 
> > give me your email address or wechat account
> 
> [codetruth@163.com](mailto:codetruth@163.com)

已发送

**Comment by rutuja1409** [comment]
Hey, I want to train on my custom dataset. But its unconditional data set, just the images, no class id no annotations. Can I still train? How can I do that?

@gasvn @xv994 @liwenyang-911 @mavenlin @P2333 Can you please help me out here if you know?

**Comment by xv994** [comment]
> Hey, I want to train on my custom dataset. But its unconditional data set, just the images, no class id no annotations. Can I still train? How can I do that?
> 
> @gasvn @xv994 @liwenyang-911 @mavenlin @P2333 Can you please help me out here if you know?

I'm sorry for replying late. 

This model is a supervised deep learning. Maybe using conditional dataset is not a right choice.
