### ISSUE TITLE
MDT-G ? 

### ISSUE THREAD

**Issue by achen46** [sail-sg/MDT#3]
Thanks for great work. In the paper, best FID results are for MDT-G. But I cannot find the config in [here](https://github.com/sail-sg/MDT/blob/main/masked_diffusion/models.py#L566). 

Can you let us know the exact config for MDT-G ?

**Comment by gasvn** [comment]
-G denotes the sampling with classifier-free guidance. It's not a new model but a sampling scheme.

**Comment by achen46** [comment]
@gasvn Thanks for the response. May I ask what is the classifier-free guidance value you used ?

**Comment by achen46** [comment]
@gasvn Also I wonder, why you choose to use a total batch size of 256 ? it seems to be more efficient to use a larger batch size like 512 but are there any reasons behind this decision ?

**Comment by gasvn** [comment]
> @gasvn Thanks for the response. May I ask what is the classifier-free guidance value you used ?

The sampling parameters are in https://github.com/sail-sg/MDT/blob/main/scripts/image_sample.py 

You can use the script in https://github.com/sail-sg/MDT#evaluation to evalute the model.

**Comment by gasvn** [comment]
> @gasvn Also I wonder, why you choose to use a total batch size of 256 ? it seems to be more efficient to use a larger batch size like 512 but are there any reasons behind this decision ?

Your are right. But to make fair comparisons with DiT, we also choose the batch size of 256.

**Comment by achen46** [comment]
@gasvn Thanks for all the prompt answers.
