### ISSUE TITLE
Evaluating

### ISSUE THREAD

**Issue by weny911** [sail-sg/MDT#33]
Dear author, I encountered this problem when I was evaluating. How do I get this **\.npz** file on my custom dataset.
![d93ae979394d51b62573900a0032648](https://github.com/sail-sg/MDT/assets/66856620/999d7a6d-f086-4745-87f7-f631104154e1)

**Comment by gasvn** [comment]
![image](https://github.com/sail-sg/MDT/assets/20515144/af57d9f0-0bde-441f-b602-76fde145a285)
check this link
