### ISSUE TITLE
Suggested settings on training b/2, s/2 ？

### ISSUE THREAD

**Issue by aaab8b** [sail-sg/MDT#39]
First of all, thank you for this wonderful work! I follow the original settings of xl/2 you provided to train mdtv2 b/2 and s/2 however the fid score calculated with imagenet 50k is much higher than the paper provided (for s/2 I got 58 fid score by using cfg when training 960k steps).  Are there any settings changed?

**Comment by gasvn** [comment]
What is the exact training setting? xl/2 uses 4x8gpu to train, while b/2 and s/2 uses 8gpu. We also list the training setting for b/2 and s/2 in our readme.

**Comment by aaab8b** [comment]
> What is the exact training setting? xl/2 uses 4x8gpu to train, while b/2 and s/2 uses 8gpu. We also list the training setting for b/2 and s/2 in our readme.

![image](https://github.com/sail-sg/MDT/assets/45478848/c42e35a8-aa80-493d-8831-ffdcb78c40f6)
look like the readme is different from the setting in your paper of N2 decoder blocks.

**Comment by gasvn** [comment]
Thanks for the reminder! Results from paper is the right setting. I will update the code

**Comment by aaab8b** [comment]
> Thanks for the reminder! Results from paper is the right setting. I will update the code

still wants to know specific decoder_layer num for B/2, or can you guys provide a public pretrain b/2 model? thank you so much.
