### ISSUE TITLE
High resolution training

### ISSUE THREAD

**Issue by Junhyuk93** [sail-sg/MDT#4]
Hello,

Thank you for sharing this amazing paper.!!
I was wondering if you have tested the model on high-resolution images (e.g., 512x512 or 1024x1024)? Have you encountered any challenges or limitations in applying the model to such high-resolution images?

**Comment by gasvn** [comment]
Thanks for your interest in our work. For now, we only train the model with 256x256 resolution. I support the larger training cost on high resolution image is the main problem we are facing.
