### ISSUE TITLE
Do I need to train a VAE myself?

### ISSUE THREAD

**Issue by feifeitu1** [sail-sg/MDT#40]
Very good job!! I am a newbie who is still in the exploration stage of deep learning. And I want to know if your training process already include transforming images into latent dimensions?Do I need to pre-train a VAE myself?
Looking forward to your answer very much. Thank you very much!!

**Comment by gasvn** [comment]
You can use a pretrained VAE, such as the VAE from stable diffusion

**Comment by feifeitu1** [comment]
Oh，Thank you for your reply. Does the training process of MDT directly load the pre-trained VAE?

**Comment by gasvn** [comment]
Yes, we follow this setting from DiT.

**Comment by feifeitu1** [comment]
OK, Thank you!!
