### ISSUE TITLE
training loss curve

### ISSUE THREAD

**Issue by yuanzhi-zhu** [sail-sg/MDT#44]
Is it possible to share the training loss curves corresponding to expr in Fig. 1
Thanks a lot in advance!

**Comment by gasvn** [comment]
[Archive.zip](https://github.com/sail-sg/MDT/files/15418116/Archive.zip)
Here is the code for Fig.1

**Comment by yuanzhi-zhu** [comment]
Thanks @gasvn , I was asking for the **training loss** curve actually.
But now I found that the training loss is not really informative....
