### ISSUE TITLE
Question about the decoder layer weights and outputs?

### ISSUE THREAD

**Issue by triton99** [sail-sg/MDT#48]
Hi @gasvn , Thank you very much for your work.

When I use MDTv2_XL_2 weight for inference, I notice that the decoder layers' output value has very big values (around 1xx - 1xxxxx). It seems strange. Is this the normal behavior of the model?

**Comment by gasvn** [comment]
I didn't check the values of the output. Does the model generate the correct image?

**Comment by triton99** [comment]
The results are acceptable; I wonder if it may cause any instability in training.

**Comment by gasvn** [comment]
I didn't encoutered the nan issue during the training on mdtv2. But still, solving this problem might leads to further performance improvement.
