### ISSUE TITLE
regarding the speed of MDT

### ISSUE THREAD

**Issue by sorobedio** [sail-sg/MDT#49]
I noticed that the code is set to use float16 mixed precision by default, which seems reasonable given that you're generating int8 integer points. This approach should not negatively impact performance.

However, I'm curious if the claimed 10x speedup is primarily due to the use of mixed precision.

**Comment by gasvn** [comment]
use_fp16 is set to false and we didn't use it. Also, the training speed test is under the same code base, so the comparsion setting is aligned.

**Comment by sorobedio** [comment]
thank you. i will be back with some questions regarding my own implementation of your work.
