### ISSUE TITLE
Inquiry of pretrained checkpoint

### ISSUE THREAD

**Issue by OliverRensu** [sail-sg/MDT#6]
Thanks for your fantastic work! May I ask when you will release the pretrained checkpoint?

**Comment by gasvn** [comment]
Thanks for waiting. The pretrained model is now on hugglingface [Pretrained model download](https://huggingface.co/shgao/MDT-XL2/tree/main), you can also download it with:
```
from huggingface_hub import snapshot_download
models_path = snapshot_download("shgao/MDT-XL2")
ckpt_model_path = os.path.join(models_path, "mdt_xl2_v1_ckpt.pt")
```
A hugglingface demo is on [DEMO](https://huggingface.co/spaces/shgao/MDT).

**Comment by alexklho** [comment]
@gasvn Can you please also provide the pretrained checkpoints of MDT-S2 and MDT-B2?

**Comment by gasvn** [comment]
Sorry, I don't have the ckpt for s2/b2 now becasue I no longer have the access to the server for training them. The training cost for s2/b2 is relatively small.
