### ISSUE TITLE
What is model MDT_S_2?

### ISSUE THREAD

**Issue by KevinWang676** [sail-sg/MDT#9]
Hi, I wonder what `--model MDT_S_2` is in the `run.sh` file. Is it just a random model name? Thank you.

**Comment by KevinWang676** [comment]
And when I tried to train the model on CIFAR-10 dataset, I got an error called `TypeError: __init__() got an unexpected keyword argument 'approximate'`. Could you help me fix this issue? Thank you! The error is shown below.

![image](https://github.com/sail-sg/MDT/assets/126712357/3d151fbe-8386-4bbf-ae06-f8775f5cde89)

**Comment by gasvn** [comment]
> Hi, I wonder what `--model MDT_S_2` is in the `run.sh` file. Is it just a random model name? Thank you.

It's the S size model with 2 patch size. We follow the DiT to name the model.

**Comment by gasvn** [comment]
> And when I tried to train the model on CIFAR-10 dataset, I got an error called `TypeError: __init__() got an unexpected keyword argument 'approximate'`. Could you help me fix this issue? Thank you! The error is shown below.
> 
> ![image](https://user-images.githubusercontent.com/126712357/245968298-3d151fbe-8386-4bbf-ae06-f8775f5cde89.png)

You can try to update your pytorch version.

**Comment by KevinWang676** [comment]
Thanks for your reply. I tried to update the pytorch version by running `pip install torch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1`. And I got another error unfortunately, which is shown below. I wonder how to fix the error called `huggingface_hub.utils._errors.LocalEntryNotFoundError`. Thanks!

![image](https://github.com/sail-sg/MDT/assets/126712357/3ac1437f-9f13-496e-a152-183241500e60)

**Comment by KevinWang676** [comment]
Hi, I tried to fix the problem by running 
```
set https_proxy=http://username:password@proxy.example.com:8080
set http_proxy=http://username:password@proxy.example.com:8080
``` 
and `pip install pylxd==2.3.0`. But I still got the same error.

**Comment by gasvn** [comment]
I didn't encounter this problem. Here is a possible solution from other repo. Maybe you can try it https://github.com/huggingface/transformers/issues/23404
